sequenceDiagram
    participant Rover_1
    participant Mothership


    Rover_1->>Mothership: Rover_ID=1, Seq=1, Type="MReq" (Pedido)
    Mothership->>Rover_1: Rover_ID=1, Seq=2, Ack_Seq=1, Type="MHan" (Atribuição)

    Note left of Rover_1: Recebe Missão. Inicia execução.

    Rover_1->>Mothership: Rover_ID=1, Seq=3, Type="MRep", Payload=".."
    Mothership->>Rover_1: Rover_ID=1, Ack_Seq=3, Type="MAck"


    Rover_1-xMothership: Rover_ID=1, Seq=4, Type="MRep", Payload=".."

    note right of Rover_1: ❌ Mensagem perdida na rede!
    note right of Mothership: (Mãe não recebe nada)

    note left of Rover_1: T1: Timeout (2s) expira. Tenta pela 2ª vez...

    Rover_1->>Mothership: Rover_ID=1, Seq=4, Type="MRep", Payload=".." (RETRY)

    note right of Mothership: Nave-Mãe recebe Seq=4 pela 1ª vez. Processa normalmente.
    Mothership->>Rover_1: Rover_ID=1, Ack_Seq=4, Type="MAck"

    note left of Rover_1: ACK recebido! Cancela timer e avança.

    Rover_1->>Mothership: Rover_ID=1, Seq=5, Type="MRep", Payload=".."