sequenceDiagram
    participant Rover_1
    participant Mothership

    Rover_1->>Mothership: Rover_ID = 1, Seq = 1, Message Type = "mission request", Payload = "..."

    Mothership->>Rover_1: Rover_ID = 1, Seq = 2, Ack_Seq = 1, Message Type = "mission handle", Payload = "..."

    Rover_1->>Mothership: Rover_ID = 1, Seq = 3, Message Type = "mission report", Payload = ".." #25%

    Mothership->>Rover_1: Rover_ID = 1, Ack_Seq = 3, Message Type = "ack"
    Rover_1->>Mothership: Rover_ID = 1, Seq = 4, Message Type = "mission report", Payload = "..."
    Mothership-xRover_1: Rover_ID = 1, Ack_Seq = 4, Message Type = "ack"

    note right of Rover_1: ❌ ACK perdido na rede!

    note left of Rover_1: T1: Timeout (2s) expira. Tenta pela 2ª vez...
    Rover_1->>Mothership: Rover_ID = 1, Seq = 4, Message Type = "mission report", Payload = "..." #50% (RETRY)

    note right of Mothership: Mothership recebe Seq=4 duplicado. Não processa a mensagem, apenas reenvia a ultima resposta enviada.
    Mothership-xRover_1: Rover_ID = 1, Ack_Seq = 4, Message Type = "ack"

    note right of Rover_1: ❌ ACK perdido outra vez!

    note left of Rover_1: T2: Timeout (4s) expira. Tenta pela 3ª vez...

    Rover_1->>Mothership: Rover_ID = 1, Seq = 4, Message Type = "mission report", Payload = "..." #50% (RETRY)

    note right of Mothership: Mothership recebe Seq=4 duplicado. Não processa a mensagem, apenas reenvia a ultima resposta enviada.
    Mothership-xRover_1: Rover_ID = 1, Ack_Seq = 4, Message Type = "ack"

    note right of Rover_1: ❌ ACK perdido outra vez!



    note left of Rover_1: Rover ignora a falta de resposta e passa para o proximo relatório.
    Rover_1->>Mothership: Rover_ID=1, Seq=5, Type="MRep", Payload="75%" (NEXT)
    Mothership->>Rover_1: Rover_ID=1, Ack_Seq=5, Type="MAck"